version: '3.8'

services:
  backend_portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://alex:10032018@postgres:5432/portfolio_db?sch>
      PORT: 9001
      BIND_HOST: 0.0.0.0
    ports:
      - '8080:9001'
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        HOST=0.0.0.0 npm run start
      "

  postgres:
    image: postgres:latest
    ports:
      - '35000:5432'
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 10032018
    volumes:
      - postgres_data:/var/lib/postgresql/data
  client_portfolio:
    build:
      context: ../portfolio-client
      dockerfile: Dockerfile
    ports:
      - '3005:4173'
    env_file:
      - ../portfolio-client/.env

volumes:
  postgres_data:
